### ISSUE TITLE
Example snippets do nothing

### ISSUE THREAD

**Issue by callumlocke** [gabrielperales/streamdeck-osascript#1]
Hi. I found this plugin in the "More actions..." list of plugins in StreamDeck, and clicked install. I came here to look for some examples. I've tried creating JavaScript actions using both of the examples from the readme. But they don't seem to do anything when I press them. I have a VS Code window open, but nothing happens.

I then tried downloading the release from this repo and installing as per the readme instructions (after uninstalling the one from the official "More actions..." dialog in StreamDeck). But it still has no efffect for either of the two examples snippets.

I am on macOS Big Sur and StreamDeck 4.9.3.

Is there anything I am missing?

**Comment by gabrielperales** [comment]
It should be just working. I know that that script can have issues if you run it on a mac with multiple screens, but otherwise, it should work.

Let me try on a mac with macOS Big Sur and I'll come back to tell you something.

**Comment by gabrielperales** [comment]
I just have tried and it seems to work also on a mac with macOS Big Sur on a m1.

Please try with a script to just open VS Code:

```
var code = Application('Visual Studio Code');

code.activate();
```

Check that you selected JavaScript on the radio buttons.
Close VS code and try pushing the button.
If it doesn't work, try closing Stream Deck and open it again.

**Comment by callumlocke** [comment]
Thanks for getting back to me so quickly. Followed your instructions. Restarting StreamDeck did the trick!

By the way, when I tried the other two examples again after restarting, it still doesn't completely work - it just opens or focuses StreamDeck, it doesn't actually do anything to resize the window for me. But that's not a problem for me, just letting you know.
